{% set name = "uncertainties" %}
{% set version = "3.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e62c86fdc64429828229de6ab4e11466f114907e6bd343c077858994cc12e00b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - future
    - pip
    - python
  run:
    - future
    - python

about:
  home: "http://uncertainties-python-package.readthedocs.io/"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Transparent calculations with uncertainties on the quantities involved (aka error propagation); fast calculation of derivatives"
  doc_url: https://uncertainties-python-package.readthedocs.io/
  dev_url: https://github.com/lebigot/uncertainties

extra:
  recipe-maintainers:
    - https://github.com/gb119
